######################################################################
# Automatically generated by qmake (3.1) Mon Mar 13 15:14:29 2017
######################################################################

TEMPLATE = app
TARGET = e1_QWidget
INCLUDEPATH += .

# Input
SOURCES += main.cpp
